In [1]:
import numpy as np

**Matrix Addition**

**Two Matrices can be added only if they have the same shape**

In [2]:
#creating the two matrices
a = np.array([[2,3],[4,5]])
b = np.array([[6,7],[8,9]])

In [3]:
print(a)
a.shape

[[2 3]
 [4 5]]


(2, 2)

In [4]:
print(b)
a.shape

[[6 7]
 [8 9]]


(2, 2)

**Addition of two matrices**

In [5]:
sum = a+b
print(sum)

[[ 8 10]
 [12 14]]


In [6]:
#cerating two matrices with random variables
m1 = np.random.randint(10,size=(3,3))
m2 = np.random.randint(20,size=(3,3))

In [7]:
print(m1)
print(m2)

[[0 1 4]
 [0 4 0]
 [4 4 9]]
[[16  9 18]
 [ 3  1 18]
 [17  6 14]]


In [8]:
sum1 = m1+m2
print(sum1)

[[16 10 22]
 [ 3  5 18]
 [21 10 23]]


In [12]:
sum2 =np.add(m1,m2)
sum2

array([[16, 10, 22],
       [ 3,  5, 18],
       [21, 10, 23]])

In [14]:
m3 = np.random.randint(10,size=(3,3))
m4 = np.random.randint(20,size=(3,4))

In [15]:
print(m3)
print(m4)

[[9 4 1]
 [2 8 2]
 [7 0 0]]
[[13  8 16 18]
 [ 9 15  1  8]
 [11 14  5  1]]


In [16]:
sum3 = m3+m4
sum3 
# we got error because of shape of m3,m4 matrices is different

ValueError: ignored

**Subtraction of two matrices**

In [9]:
sub=b-a
print(sub)

[[4 4]
 [4 4]]


In [19]:
#cerating two matrices with random variables
m5 = np.random.randint(10,size=(3,3))
m6 = np.random.randint(20,size=(3,3))

In [20]:
print(m5)
print(m6)

[[0 7 1]
 [2 4 1]
 [4 5 1]]
[[18 14 12]
 [ 5 13 14]
 [ 7 17 13]]


In [21]:
sub2 = m5-m6
sub2

array([[-18,  -7, -11],
       [ -3,  -9, -13],
       [ -3, -12, -12]])

**Multiplication of matrices by a scaler**

In [22]:
x = 5
y = np.array([2,3,4])
mul = x*y
print(mul)

[10 15 20]


In [23]:
x1 = 5
y1 = np.random.randint(10, size=(4,4))
mul1 = x1*y1
mul1

array([[ 5, 15, 25, 35],
       [ 0, 35, 10, 30],
       [25, 20, 20,  0],
       [15, 35, 20,  0]])

**Multiplying the two matrices**

In [30]:
m7 = np.random.randint(5,size=(3,3))
m8 = np.random.randint(5,size=(3,4))

In [33]:
print(m7)
print(m8)

[[3 3 2]
 [1 3 3]
 [0 1 3]]
[[1 0 2 3]
 [1 3 3 1]
 [4 1 2 4]]


(3, 4)

In [34]:
m7.shape

(3, 3)

In [35]:
m8.shape

(3, 4)

In [32]:
product = np.dot(m7,m8)
print(product)

[[14 11 19 20]
 [16 12 17 18]
 [13  6  9 13]]


In [44]:
m9 = np.random.randint(5,size=(3,3))
m10 = np.random.randint(5,size=(3,3))

In [45]:
print(m9)
print(m10)

[[4 0 0]
 [0 3 4]
 [1 0 1]]
[[3 0 2]
 [2 4 0]
 [0 1 4]]


In [47]:
mul2 = np.multiply(m9,m10)
mul2

array([[12,  0,  0],
       [ 0, 12,  0],
       [ 0,  0,  4]])