In [1]:
import numpy as np

**Creating a Matrix using Numpy**

In [2]:
m1 = np.array([[2,3],[6,7]])
print(m1)

[[2 3]
 [6 7]]


In [3]:
m2 = np.array([[2,3],[6,7]])
print(m2)

[[2 3]
 [6 7]]


In [5]:
m1.shape
m2.shape

(2, 2)

In [4]:
print(m1+m2)

[[ 4  6]
 [12 14]]


In [6]:
m3 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(m3)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [7]:
m3.shape

(3, 3)

**Creating Matrices with random values**

In [9]:
rm = np.random.rand(3,3)
print(rm)

[[0.27197722 0.88720573 0.61330858]
 [0.76464977 0.69389847 0.10084763]
 [0.81058352 0.37403802 0.92693797]]


In [11]:
# Creating matrix with random integers
rmi = np.random.randint(100, size=(3,3))
print(rmi)

[[82 49 64]
 [33 41 89]
 [75 77 29]]


**Matrix with all values as one**

In [12]:
m4 = np.ones((2,3))
print(m4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
m5 = np.ones((2,3), dtype=int)
print(m5)

[[1 1 1]
 [1 1 1]]


In [14]:
m5 = np.ones((4,4), dtype=int)
print(m5)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


**Matrix with all values as Zeros:null matrix or zero matrix**

In [15]:
m6 = np.zeros((4,4))
print(m6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
m7 = np.zeros((4,4), dtype=int)
print(m7)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**Identity matrix**

In [18]:
m8 = np.eye(4,4)
print(m8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Transpose of a Matrix**

In [20]:
# Matrix with random integers values
a = np.random.randint(100,size=(4,5))
print(a)

[[88 85 94 64 27]
 [87 99 97  1 18]
 [78 56 97 77 58]
 [78 28 43 29 58]]


In [21]:
transpose = np.transpose(a)
print(transpose)

[[88 87 78 78]
 [85 99 56 28]
 [94 97 97 43]
 [64  1 77 29]
 [27 18 58 58]]
